# =========================
# Configuración del servidor
# =========================
server.port=${PORT:8080}
spring.application.name=SafePlay

# =========================
# Configuración de la base de datos PostgreSQL (Render)
# =========================
spring.datasource.url=jdbc:postgresql://dpg-d2keurndiees73c4otug-a:5432/safeplay_db_immv
spring.datasource.usern ame=user_safe
spring.datasource.password=g8SkFW7wWU1QxK3s6RGJ8dgbmoV0nrzr
spring.datasource.driver-class-name=org.postgresql.Driver

# =========================
# JPA / Hibernate
# =========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
